<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flashSession->output(); ?>
    <div id="edit_list">
        <form name="edit_list" method="post" action="saveTitle">
            <label for="current_title">Current Title: </label>
            <input id="current_title" name="list_title" type="text" value="<?php echo $list->title; ?>" disabled>

            <label for="new_title">New Title: </label>
            <input id="new_title" name="new_title" type="text" maxlength="50" placeholder="Enter new title">
            <input name="list_id" value="<?php echo $list->id; ?>" hidden>
            <div id="edit_controls">
                <input class="btn btn-success" type="submit" value="Save">
                <a class="btn btn-danger" id="cancel" href="/edit/">Cancel</a>
            </div>
        </form>
    </div>
    <div id="members">
        <h3>Members of this list</h3>
        <div>
            <?php

            $html = '';

            if(count($members) < 1) {

                $html .= '<p>There are no members to this list yet</p>' . "\n";

            } else {

                $html .= '<table>' . "\n";

                foreach($members as $member) {

                    $html .= '<tr>' . "\n";
                    $html .= '<td><span id="i' . $member['user_id'] . '">' . $member['username'] . '</span></td>' . "\n";
                    $html .= '<td><button class="btn btn-danger btn-small delete_member pull-right"><i class="icon-white icon-remove"></i></button></td>' . "\n";
                    $html .= '</tr>' . "\n";

                }

                $html .= '</table>' . "\n";

            }

            echo $html;

            ?>
        </div>
    </div>