<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flash->output(); ?>
    <div id="invitations">
        <h3>Your invitations</h3>

        <?php

        $html = '';

        if(count($invitations) < 1) {

            $html .= '<p>There are no invitations for you at the moment</p>' . "\n";

        } else {

            $html .= '<ul>' . "\n";

            foreach($invitations as $invitation) {

                $inviter = Users::findFirst("id = {$invitation->owner_id}");
                $list = Lists::findFirst("id = {$invitation->list_id}");

                $html .= '<li>' . "\n";
                $html .= '<div>' . "\n";
                $html .= '<p>';
                $html .= 'You have been invited by ';
                $html .= $inviter->username;
                $html .= ' to the list: <br/>';
//                $html .= '</p>' . "\n";
//                $html .= '<p>' . "\n";
                $html .= '<span class="list_title">' . $list->title . '</span>' . "\n";
                $html .= '</p>' . "\n";
                $html .= '</div>' . "\n";

                $html .= '<div class="holder">' . "\n";

                $html .= Phalcon\Tag::form(array("invitations/acceptInvitation", "method" => "post", "name" => "accept_invitation_{$invitation->id}")) . "\n";
                $html .= '<input name="invitation_to_accept" type="hidden" value="' . $invitation->id . '">' . "\n";
                $html .= '<label class="btn btn-success btn-small" for="accept_invitation_' . $invitation->id . '"><i class="icon-white icon-ok"></i></label>' . "\n";
                $html .= '<input class="hidden" type="submit" id="accept_invitation_' . $invitation->id . '">' . "\n";
                $html .= Phalcon\Tag::endForm() . "\n";

                $html .= Phalcon\Tag::form(array("invitations/deleteInvitation", "method" => "post", "name" => "delete_invitation_{$invitation->id}")) . "\n";
                $html .= '<input name="invitation_to_delete" type="hidden" value="' . $invitation->id . '">' . "\n";
                $html .= '<label class="btn btn-danger btn-small" for="delete_invitation_' . $invitation->id . '"><i class="icon-white icon-remove"></i></label>' . "\n";
                $html .= '<input class="hidden" type="submit" id="delete_invitation_' . $invitation->id . '">' . "\n";
                $html .= Phalcon\Tag::endForm() . "\n";

                $html .= '</div>' . "\n";

                $html .= '</li>' . "\n";

            }

            $html .= '</ul>' . "\n";

        }

        echo $html;

        ?>

        <!--
        <?php

        $html = '';

        $html .= '<table>' . "\n";
        //TODO add table head

        if(count($invited) < 1) {

            $html .= '<tr>' . "\n";
            $html .= '<td>There are no invitations for you at the moment</td>' . "\n";
            $html .= '</tr>' . "\n";

        } else {

            foreach($invited as $inv) {

                $html .= '<tr>' . "\n";
                $html .= '<td>You have been invited by ' . $inv['username'] . ' to the list <span id="i' . $inv['list_id'] . '">' . $inv['list_title'] . '</span></td>' . "\n";
                $html .= '<td><button class="btn btn-success btn-small accept_invited pull-right"><i class="icon-white icon-ok icon-accept"></i> </button></td>' . "\n";
                $html .= '<td><button class="btn btn-danger btn-small delete_invited pull-right"><i class="icon-white icon-remove"></i> </button></td>' . "\n";
                $html .= '</tr>' . "\n";

            }

        }

        $html .= '</table>' . "\n";

        echo $html;

        ?>
    </div>
    -->

</div>