<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flash->output(); ?>
    <div id="invited">
        <h3>Your invitations</h3>
        <?php

        $html = '';

        $html .= '<table>' . "\n";
        //TODO add table head

        if(count($invited) < 1) {

            $html .= '<tr>' . "\n";
            $html .= '<td>There are no invitations for you at the moment</td>' . "\n";
            $html .= '</tr>' . "\n";

        } else {

            foreach($invited as $inv) {

                $html .= '<tr>' . "\n";
                $html .= '<td>You have been invited by ' . $inv['username'] . ' to the list <span id="i' . $inv['list_id'] . '">' . $inv['list_title'] . '</span></td>' . "\n";
                $html .= '<td><button class="btn btn-success btn-small accept_invited pull-right"><i class="icon-white icon-ok icon-accept"></i> </button></td>' . "\n";
                $html .= '<td><button class="btn btn-danger btn-small delete_invited pull-right"><i class="icon-white icon-remove"></i> </button></td>' . "\n";
                $html .= '</tr>' . "\n";

            }

        }

        $html .= '</table>' . "\n";

        echo $html;

        ?>
    </div>
</div>