<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flashSession->output(); ?>
    <div id="lists">
        <h2>My Lists:</h2>

        <form action="" method="get" name="load_list">
            <?php echo $form->render('list'); ?>
            <?php echo $form->render('Load'); ?>
        </form>


    </div>

    <div id="items">
        <div id="items_container">
            <table>
                <?php

                $html = '';

                foreach($items as $item) {
                    $item_class = '';
                    if($item->tapped) {
                        $item_class = 'item_name tapped';
                    } else {
                        $item_class = 'item_name untapped';
                    }

                    $html .= '<tr class="' . $item_class . '">' . "\n";
                    $html .= '<td class="item_title" id="i' . $item->id . '">' . $item->name . '</td>';
                    $html .= '<td><button class="btn btn-danger btn-small delete_item item_action"><i class="icon-white icon-remove"></i> </button></td>' . "\n";
                    $html .= '</tr>' . "\n";

                }

                echo $html;

                ?>
            </table>
        </div>
        <div id="item_input">
            <form name="add_item" method="post" action="addItem">
                <input name="item_to_add" type="text" maxlength="200">
                <input id="working_list" name="working_list" type="hidden" value="<?php echo $current_list->id; ?>">
                <input name="add_item" class="btn btn-primary" type="submit" value="Add" >
            </form>
        </div>
    </div> <!-- end #items -->
</div>