<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flashSession->output(); ?>
    <div id="lists">
        <h2>My Lists:</h2>

        <form action="/member/" method="post" name="load_list">
            <select id="select_list" name="list" class="form-control">
                <?php

                $html = '';

                foreach($user_lists as $ul) {

                    if($ul == $current_list) {

                        $html .= '<option value="' . $ul->id . '" selected>' . $ul->title . '</option>' . "\n";

                    } else {

                        $html .= '<option value="' . $ul->id . '">' . $ul->title . '</option>' . "\n";

                    }
                }

                echo $html;

                ?>
            </select>
        </form>

    </div>

    <div id="items">
        <div id="items_container">
            <?php

            $html = '';

            if(count($items) < 1) {

                $html .= '<p>You haven\'t add any items yet.</p>' . "\n";

            } else {

                $html .= '<table>' . "\n";

                foreach($items as $item) {
                    $item_class = '';
                    if($item->tapped) {
                        $item_class = 'item_name tapped';
                    } else {
                        $item_class = 'item_name untapped';
                    }

                    $html .= '<tr class="' . $item_class . '">' . "\n";
                    $html .= '<td class="item_title" id="i' . $item->id . '">' . $item->name . '</td>';
                    $html .= '<td><button class="btn btn-danger btn-small delete_item item_action pull-right"><i class="icon-white icon-remove"></i> </button></td>' . "\n";
                    $html .= '</tr>' . "\n";

                }

                $html .= '</table>' . "\n";

            }

            echo $html;

            ?>
            </table>
        </div>
        <div id="item_input">
            <form name="add_item" method="post" action="/member/addItem">
                <input name="item_to_add" type="text" maxlength="200">
                <input id="working_list" name="working_list" type="hidden" value="<?php echo $current_list->id; ?>">
                <input name="add_item" class="btn btn-primary pull-right" type="submit" value="Add" >
            </form>
        </div>
    </div> <!-- end #items -->
</div>