<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flashSession->output(); ?>
    <div id="lists">
        <h2>My Lists:</h2>

        <?php

        if(count($user_lists) > 0) {
            echo Phalcon\Tag::form(array("member/", "method" => "post", "name" => "load_list")) . "\n";
            echo $listselectform->render('select') . "\n";
            echo Phalcon\Tag::endForm() . "\n";
        } else {

            $html = '';

            $html .= '<p>You haven\'t made any lists yet.</p>' . "\n";
            $html .= '<p class="link"><span id="create_list" class="btn btn-primary">Create a List</span></p>' . "\n";

            echo $html;
        }

        ?>

    </div>

    <div id="items">
        <div id="items_container">

            <?php $this->partial('partials/items'); ?>

        </div>
        <div id="item_input">

            <?php if(count($user_lists) > 0) { ?>
            <?php echo Phalcon\Tag::form(array("member/addItem", "method" => "post")) . "\n"; ?>
            <?php echo $itemform->render("item_name") . "\n"; ?>
            <?php echo $itemform->render("working_list") . "\n"; ?>
            <?php echo $itemform->render("Add") . "\n"; ?>
            <?php echo Phalcon\Tag::endForm() . "\n"; ?>
            <?php } ?>

        </div>
    </div> <!-- end #items -->
</div>