<?php $this->partial('partials/publicHeader'); ?>

<p>
    Lister is a simple list-making application for creating and sharing one dimensional lists.
    The application is free to use, however, the project is mainly a programming exercise and the stability of the
    application is not guaranteed.
</p>
<p>
    The application itself was coded from scratch in PHP and MySQL at first - you can test that version <a href="">here</a>
    if you like - which basically is an initial attempt at home-made MVC. To get some more experience with frameworks I
    decided to redo this project in <a href="http://www.phalconphp.com/en/">Phalcon framework</a> and
    <a href="http://getbootstrap.com/">Twitter Bootstrap</a>
</p>
<p>
    If you like/hate the project, or you want to send me an email for whatever reasons, you can find me at
    <a href="mailto:dev@martinussen.email">dev@martinussen.email</a>.
</p>
