<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flash->output(); ?>
    <div id="add_list_form">

        <?php echo Phalcon\Tag::form(array("edit/addList", "method" => "post", "name" => "add_list")) . "\n"; ?>
        <?php echo $addListForm->label('list_title') . "\n"; ?>
        <?php echo $addListForm->render('list_title') . "\n"; ?>
        <?php echo $addListForm->render('Add') . "\n"; ?>
        <?php echo Phalcon\Tag::endForm() . "\n"; ?>

    </div>
    <div id="lists">
        <?php

        $html = '';

        if(count($lists) < 1) {

            $html .= '<p>You haven\'t made any lists yet</p>' . "\n";

        } else {

            $html .= '<ul>' . "\n";

            foreach($lists as $list) {

                $member_url = '/member/list/' . $list->id . '/';
                $editlist_url = '/editlist/list/' . $list->id . '/';

                if($list->owner_id == $user->id) {
                    $participation = 'owner';
                } else {
                    $participation = 'member';
                }

                $html .= '<li id="l' . $list->id . '">' . "\n";

                $html .= '<p><a href="' . $member_url . '">' . $list->title . '</a></p>' . "\n";
                $html .= '<div class="holder">' . "\n";
                $html .= '<a href="/edit/users/' . $list->id . '/" class="btn btn-warning btn-small"><i class="icon-white icon-user"></i></a>' . "\n";
                $html .= '<a href="/edit/list/' . $list->id . '/" class="btn btn-warning btn-small"><i class="icon-white icon-edit"></i></a>' . "\n";
                $html .= Phalcon\Tag::form(array("edit/deleteList", "method" => "post", "name" => "delete_list_{$list->id}", "onsubmit" => "return confirm('Delete the list?');")) . "\n";
                $html .= '<input name="list_to_delete" type="hidden" value="' . $list->id . '">' . "\n";
                $html .= '<input type="hidden" name="participation" value="' . $participation . '">' . "\n";
                $html .= '<label class="btn btn-danger btn-small" for="delete_list_' . $list->id . '"><i class="icon-white icon-remove"></i></label>' . "\n";
                $html .= '<input class="hidden" type="submit" id="delete_list_' . $list->id . '">' . "\n";
                $html .= Phalcon\Tag::endForm() . "\n";

                $html .= '</div>' . "\n";

                $html .= '</li>' . "\n";

            }

            $html .= '</ul>' . "\n";
        }

        echo $html;

        ?>
    </div>
</div>