<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flash->output(); ?>
    <div id="edit_list">

        <?php echo Phalcon\Tag::form(array("edit/saveTitle", "method" => "post", "name" => "edit_list")) . "\n"; ?>
        <?php echo $editListForm->label('current_title') . "\n"; ?>
        <?php echo $editListForm->render('current_title') . "\n"; ?>
        <?php echo $editListForm->label('new_title') . "\n"; ?>
        <?php echo $editListForm->render('new_title') . "\n"; ?>
        <?php echo $editListForm->render('list_id') . "\n"; ?>
        <div id="edit_controls">
            <?php echo $editListForm->render('Save') . "\n"; ?>
            <a class="btn btn-danger" id="cancel" href="/edit/">Cancel</a>
        </div>
        <?php echo Phalcon\Tag::endForm() . "\n"; ?>

    </div>

    <!--
    <div id="members">
        <h3>Members of this list</h3>
        <div>
            <?php

            $html = '';

            if(count($members) < 1) {

                $html .= '<p>There are no members to this list yet</p>' . "\n";

            } else {

                $html .= '<table>' . "\n";

                foreach($members as $member) {

                    $html .= '<tr>' . "\n";
                    $html .= '<td><span id="i' . $member->member_id . '">' . Users::findFirst("id = {$member->member_id}")->username . '</span></td>' . "\n";
                    $html .= '<td><button class="btn btn-danger btn-small delete_member pull-right"><i class="icon-white icon-remove"></i></button></td>' . "\n";
                    $html .= '</tr>' . "\n";

                }

                $html .= '</table>' . "\n";

            }

            echo $html;

            ?>
        </div>
        -->

    </div>