<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flash->output(); ?>
    <div id="edit_list">

        <?php echo Phalcon\Tag::form(array("edit/saveTitle", "method" => "post", "name" => "edit_list")) . "\n"; ?>
        <?php echo $editListForm->label('current_title') . "\n"; ?>
        <?php echo $editListForm->render('current_title') . "\n"; ?>
        <?php echo $editListForm->label('new_title') . "\n"; ?>
        <?php echo $editListForm->render('new_title') . "\n"; ?>
        <?php echo $editListForm->render('list_id') . "\n"; ?>
        <div id="edit_controls">
            <?php echo $editListForm->render('Save') . "\n"; ?>
            <a class="btn btn-danger" id="cancel" href="/edit/">Cancel</a>
        </div>
        <?php echo Phalcon\Tag::endForm() . "\n"; ?>

    </div>

</div>