<?php $this->partial('partials/memberHeader'); ?>
<div>
    <?php echo $this->flashSession->output(); ?>
    <div id="change_password">
        <h3>Change Password</h3>

        <?php echo Phalcon\Tag::form(array("profile/changePassword", "method" => "post", "name" => "change_password")) . "\n"; ?>
        <?php echo $changePasswordForm->render('current_password') . "\n"; ?>
        <?php echo $changePasswordForm->render('new_password') . "\n"; ?>
        <?php echo $changePasswordForm->render('repeat_password') . "\n"; ?>
        <?php echo $changePasswordForm->render('Change Password') . "\n"; ?>
        <?php echo Phalcon\Tag::endForm() . "\n" ?>

    </div>
    <div id="change_email">
        <h3>Change Email</h3>

        <?php echo Phalcon\Tag::form(array("profile/changeEmail", "method" => "post", "name" => "change_email")) . "\n" ?>
        <?php echo $changeEmailForm->render('current_email') . "\n"; ?>
        <?php echo $changeEmailForm->render('new_email') . "\n"; ?>
        <?php echo $changeEmailForm->render('repeat_email') . "\n"; ?>
        <?php echo $changeEmailForm->render('Change Email') . "\n"; ?>
        <?php echo Phalcon\Tag::endForm() . "\n"; ?>

    </div>
</div>